#! /bin/bash
# /etc/init.d/airpibootstart

### BEGIN INIT INFO
# Provides:          airpi
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start AirPi at boot if required.
# Description:       Check AirPi config file to see if AirPi should start sampling automatically on booting.
### END INIT INFO

# =============================================================================
# File:     airpibootstart
# Requires: airpi.py
# Purpose:  Start AirPi at boot if required.
# Comments: Check AirPi config file to see if AirPi should start sampling
#           automatically on booting. If so, start sampling.
# Author:   Haydn Williams <pi@hwmail.co.uk>
# Date:     August 2014
# =============================================================================

case "$1" in
    start)
        # This script uses the "bootstart" option in the AirPi settings file to decide
        # whether the AirPi should start sampling automatically.

        if `ps aux | grep -v "grep" | grep -q "sudo.*airpi.py"`; then
            echo "[AirPi] Error - it looks like the AirPi is already running."
            exit 1
        fi

        # Set path to Airpi directory and settings file
        AIRPI_DIR=/home/pi/AirPi
        CFG_DIR=cfg
        AIRPI_SETTINGS=settings.cfg

        # Start the main AirPi script if requested in the settings file 
        echo "[AirPi] Checking whether AirPi should start sampling automatically..."
        if grep -qiE "^(bootstart).*(yes|true|on)$" $AIRPI_DIR/$CFG_DIR/$AIRPI_SETTINGS; then
            echo "[AirPi] Will start automatic sampling in one minute."
            sleep 60
            echo "[AirPi] Starting automatic AirPi sampling in background process."
            sudo python $AIRPI_DIR/airpi.py &
        else
            echo "[AirPi] Automatic AirPi sampling not requested." 
        fi
    ;;
    stop)
        echo "[AirPi] Stopping all AirPi sampling."
        echo "[AirPi] Alternatively you could use ./airpictl.sh stop"
        # Remember AirPi could be started any number of ways, including:
        # sudo python airpi.py
        # sudo python ./airpi.py
        # sudo ./airpi.py
        if `ps aux | grep -v "grep" | grep -q "sudo.*airpi.py"`; then
            kill `ps aux | grep -v "grep" | grep "sudo.*airpi.py" | awk '{print $2}'`
        fi
    ;;
    *)
        echo "Usage: /etc/init.d/airpibootstart {start|stop}"
        exit 1
    ;;
esac

exit 0
